### ISSUE TITLE
一つひとつは許容したい

### ISSUE THREAD

**Issue by moesuke** [progedu/textlint-rule-preset-dwango-progedu#14]
1 つ 1 つになってしまうのが気になるので。

**Comment by sifue** [comment]
自分もそうしたいと思います。
これ許容しませんかね？結構じぶんも困ってます。直してしまいますね。

**Comment by sifue** [comment]
https://github.com/progedu/textlint-rule-preset-dwango-progedu/commit/ef99a68398247a88393aa254728aec9fdeefb89a

こちらで対応し、1.1.9としてリリースしました。

```sh
 npm uninstall textlint-rule-preset-dwango-progedu
 npm i --save-dev textlint-rule-preset-dwango-progedu@1.1.9
```

で対応可能です。利用ください。これにて完了とします。
