### ISSUE TITLE
Radius => RADIUS のルールを削除したい

### ISSUE THREAD

**Issue by mikrogeophagus** [progedu/textlint-rule-preset-dwango-progedu#15]
Unity の教材で修正の必要がない箇所で指摘されてしまうため、Radius => RADIUS のルールを textlint-rule-preset-dwango-progedu から削除したいです。このルールが必要な教材があればプロジェクト独自で設定するようにしたいです。

**Comment by moesuke** [comment]
@mikrogeophagus 
検索した感じ大文字 `RADIUS` は一箇所しかなかったので、削除でいいとおもいます。
